### ISSUE TITLE
Tracking issue for nodes' hover panel and bottom panel

### ISSUE THREAD

**Issue by Daanish-Khan** [SEG491X-W2023-T42/mikado-machine#10]
Currently there is no options to edit nodes. We need to create a control panel UI that allows users to edit nodes if necessary.

# Steps

- #31
- #33
- #34
- #35
- #36
- #37
- #38
- #39
- #40
- #41
- #42

**Comment by danielzgtg** [comment]
Claiming this as it may be affected by my work on #31.

I think I will naturally implement this as I close my tabs open to the React Flow documentation, with around one commit per tab.

**Comment by danielzgtg** [comment]
Closing this high-priority issue as all required parts are implemented. The only thing remaining is wishlist-priority.
