### ISSUE TITLE
Make icons on leaf nodes less confusing

### ISSUE THREAD

**Issue by jodiqiao** [SEG491X-W2023-T42/mikado-machine#112]
At our April 19 meeting where we received our second round of feedback in the fall semester of SEG4910 in 2023, our client indicated he found our current use of icons confusing.

Ad-libbed by our client:

1. want visual icons to be more intuitive for its intended meaning
2. ~~wants text in addition to icon~~

**Comment by philippe-gagne** [comment]
The icon on the locked nodes will also be changed to be clearer. I will email Andriy to get his opinion on options for leaf node icons.
