### ISSUE TITLE
Allow user to change node colours

### ISSUE THREAD

**Issue by jodiqiao** [SEG491X-W2023-T42/mikado-machine#113]
At our April 19 meeting where we received our second round of feedback in the fall semester of SEG4910 in 2023, our client questioned our use of colours for nodes.

Use of colours on nodes communicate node types and statuses.

Client has indicated in past meetings a preference for quality aesthetics, although he has also said he doesn't care much for our choice of colours so long as things look good and make sense. This feels a bit contradictory, we might have to consult some UI colour theories to reason our colour selections better, or the more effortful (possibly wasteful) option to implement functionality to allow user to customize colours. Further discussion may be needed.

**Comment by Daanish-Khan** [comment]
closing as there is no time to complete this task
