### ISSUE TITLE
Remove FAB on desktop

### ISSUE THREAD

**Issue by philippe-gagne** [SEG491X-W2023-T42/mikado-machine#120]
As node creation will be moved to a double-click, the FAB is no longer needed on desktop. This will require media queries for device detection to be in place and two diverging feature branches for computers and mobile.

Also see #115

**Comment by danielzgtg** [comment]
Already removed in 4b7781556a38c32ce47c37384f64f74dc3bd9fac because I needed to remove `DisplayLayerHandle.js`. We will bring it back after we clean up the code and remove `EnterGraphHackContext.js`.
