### ISSUE TITLE
Graph is blurry after starting editing text on Safari

### ISSUE THREAD

**Issue by danielzgtg** [SEG491X-W2023-T42/mikado-machine#142]
On Safari/Epiphany, the whole graph becomes blurry once editing starts. It starts when text is typed to be added after entering editing mode. It stops after editing finishes or if the graph is zoomed out and back in.

# Slightly blurry on Safari
https://github.com/SEG491X-W2023-T42/mikado-machine/assets/25646384/36b9f3d1-16ab-4cfe-bbe8-c5af0d8cdaf6

# Very blurry on Epiphany
https://github.com/SEG491X-W2023-T42/mikado-machine/assets/25646384/f0e4c231-f125-4608-96b4-f2a55ddc04f9

**Comment by Daanish-Khan** [comment]
closing as we dont have time to investigate issue
