### ISSUE TITLE
React project folder refactor

### ISSUE THREAD

**Issue by philippe-gagne** [SEG491X-W2023-T42/mikado-machine#162]

**Comment by danielzgtg** [comment]
The folder structure should look somewhat like the following as discussed:

```
- src/
  - pages
    - Graph
    - Opener
    - Login
  - graph
    - component
    - store
  - layer
    - component
    - store
  - user`
```

This is only part 1 of the refactor to support new graphs and the database refactor. Part 2 will be done together with the database and new graph feature changes.
