### ISSUE TITLE
Make the questline overlay open the screen

### ISSUE THREAD

**Issue by danielzgtg** [SEG491X-W2023-T42/mikado-machine#171]
For https://github.com/Daanish-Khan/seg4105_project/tree/main/pitches/questline , continuing https://github.com/danielzgtg/seg4105_playground/tree/main/lab06

**Comment by Daanish-Khan** [comment]
closed by commit in https://github.com/SEG491X-W2023-T42/mikado-machine/tree/169-task-list-screen
