### ISSUE TITLE
Replace sign in flow with "Sign in to Mikado with Google" prompt

### ISSUE THREAD

**Issue by danielzgtg** [SEG491X-W2023-T42/mikado-machine#32]
Our professor is concerned that our current sign in flow in insecure. He is worried that clicking the button is a security risk.

The sign in flow should be with a more modern alternative. The old button is still needed in case the new automatic flow is cancelled, but it should be made less visible. There is a new "Sign in to WEBSITE with Google" style that has been suggested and is becoming more popular across the web:

LinkedIn's automatic sign in:

![image](https://user-images.githubusercontent.com/25646384/219057659-553ff584-d85f-4c5e-bd4a-5622144ee856.png)

Medium's prompt, but I didn't create an account yet:

![image](https://user-images.githubusercontent.com/25646384/219057826-505e2607-1934-422c-a729-ac1a864fe496.png)

Since it shows the name, profile picture, and email already, (even though the information technologically isolated from the website until it's activated) the user may perceive that there is less additional personal information they need to disclose.

**Comment by Daanish-Khan** [comment]
closing as there is no time to complete this task
