### ISSUE TITLE
Strange behavior while trying to connect nodes

### ISSUE THREAD

**Issue by danielzgtg** [SEG491X-W2023-T42/mikado-machine#5]
There is a strange problem where random connections appear when I try to connect nodes.

# Expected Behavior

Connecting two unconnected nodes results in a connection between them.

# Actual Behavior

The second node gets connected to random other nodes as well:

https://user-images.githubusercontent.com/25646384/218244376-0c4b7254-b315-4aa0-ae58-a89d37d570f5.mp4

**Comment by Daanish-Khan** [comment]
The initial state of the graph is incorrect. The 3 nodes are supposed to be connected together, however the state is not updated until you add a node. Happened on my end but don't know why this happens as its only occasional.
