### ISSUE TITLE
Reverse the arrow directions

### ISSUE THREAD

**Issue by danielzgtg** [SEG491X-W2023-T42/mikado-machine#55]
As requested by our client.

We should do this at the `graphTheme.js`. Messing with `displayLayerStore.js` may cause regressions.

**Comment by Daanish-Khan** [comment]
Directions already working as intended.

**Comment by danielzgtg** [comment]
This needs to be reopened. The client specifically told us to reverse the behavior of the status quo when we showed it to him.

Working as intended by our design is not working as intended for the client.
