### ISSUE TITLE
Add nodes to the center of the screen

### ISSUE THREAD

**Issue by danielzgtg** [SEG491X-W2023-T42/mikado-machine#57]
We discussed and decided the best user experience is to never silently fail when adding nodes. Nodes should be added to the centre of the screen whenever possible (not intersecting). When not possible, we could keep tryinging after shifting to the bottom right. This issue covers the business logic in `DisplayLayer`, `DisplayLayerHandle`, and `DisplayLayerOperations`.

**Comment by Daanish-Khan** [comment]
linked to #56 as implementing this was en route with the FAB implementation of adding a node.

**Comment by Daanish-Khan** [comment]
Instead of adding to middle, nodes now add to top right of screen to maximize space
