### ISSUE TITLE
Fix add node relative positioning

### ISSUE THREAD

**Issue by danielzgtg** [SEG491X-W2023-T42/mikado-machine#75]
The add node feature from the FAB is using document coordinates. We can't assume they will equal the graph container element coordinates if a header is added. This is an architectural problem, and may block the subgraph feature from being added as that may introduce a title bar with a back button. See https://reactflow.dev/docs/examples/nodes/add-node-on-edge-drop/ for code examples. The code that needs changing is https://github.com/SEG491X-W2023-T42/mikado-machine/blob/9ba588ea40ce5cfc87042e0a19489d48d030a300/mikado-app/src/pages/Graph/DisplayLayer.js#L75-L81

**Comment by danielzgtg** [comment]
This might be visually reproducible now that #82 is merged. We should confirm with a video if this bug actually manifests. If it is not possible to reproduce this we can either close this, or leave this as a documentation/refactor fix. Note that on normal screen sizes, the user would need to pay attention to notice this, but would not unsee it.

**Comment by Daanish-Khan** [comment]
ah for this issue the graph container element didnt change. The header is on top of the graph on the z axis via positioning
