### ISSUE TITLE
Draw internal animation state/sequence diagrams

### ISSUE THREAD

**Issue by danielzgtg** [SEG491X-W2023-T42/mikado-machine#83]
Confusion about the infrastructure to support the goal nodes feature and its animations needs to be addressed. A set of sequence and state diagrams would be helpful. We need diagrams for the behaviour of the buttons and the lifecycles of View/ViewModel components. We need synchronization diagrams, especially for how the DisplayLayers get created, animated, and destroyed.

**Comment by Daanish-Khan** [comment]
closing as there is no time to complete this task + is now low prio.
