### ISSUE TITLE
Add edit graph name feature

### ISSUE THREAD

**Issue by Daanish-Khan** [SEG491X-W2023-T42/mikado-machine#85]
With the new app bar, we need the ability to chagne the graph name.

**Comment by danielzgtg** [comment]
This should be tied to the goal node containing it.

**Comment by danielzgtg** [comment]
If it's the root layer of a graph, then it can be edited on the welcome screen. There you would pick the graph to open.

**Comment by danielzgtg** [comment]
Layer name is goal node name. The title at the top of the screen is the graph title. Double click to edit it, and don't show the text box unless clicked. Don't need to show the layer name in the title. Show the same graph name for all layers
