### ISSUE TITLE
Create new graph feature

### ISSUE THREAD

**Issue by Daanish-Khan** [SEG491X-W2023-T42/mikado-machine#87]
With the new app bar, we are able to add buttons to the bar. Please implement a feature that would allow the user to create a new graph with a specified name (optional, otherwise defaults to graph-x, where x is the number of graphs the user has + 1).

**Comment by danielzgtg** [comment]
We should default to "Untitled Graph".

> where x is the number of graphs the user has + 1

This may cause heavy database usage if it's has to query the collection with all the user's graphs. The total count should not be stored either because there is a risk that might go out of sync if there are network or synchronization problems.

**Comment by Daanish-Khan** [comment]
what if there are multiple "untitiled graphs"? How can we differentiate between the two

**Comment by danielzgtg** [comment]
We can differentiate between multiple "untitiled graphs" in the same way Google Docs and other apps can differentiate between multiple documents with the same name. This only adds a new label to show to the user instead, and hides the actual name (a.k.a what we previously called the name) from the user. Each and every button and database-related function will still have the old ID. See #88

**Comment by danielzgtg** [comment]
> with a specified name

Actually, no. This creates too much friction. Let's just have the app create open a new untitled graph directly like Google Docs and Microsoft Word. The user can rename it right after it's created using the rename graph (anytime) feature. This would avoid adding an extra way to do things, simplifying the app for both users and developers.

**Comment by Daanish-Khan** [comment]
closed with #211
